-- Seed data for the public broker profile.
-- Populates a single broker (Paulo Leal Saviñón) plus 6 Monterrey listings.
-- Running `supabase db reset` (or `psql ... -f seed.sql`) against a fresh DB
-- bootstrapped from the migrations will give a fully functional public site.

begin;

-- ---------------------------------------------------------------------------
-- Broker
-- ---------------------------------------------------------------------------

insert into public.brokers (
  slug,
  nombre,
  headline,
  bio_corta,
  bio_larga,
  foto_url,
  banner_url,
  telefono,
  whatsapp,
  email,
  instagram,
  facebook,
  linkedin,
  ciudad,
  anios_experiencia,
  certificaciones,
  zonas_especializacion,
  stats
) values (
  'paulo-leal',
  'Paulo Leal Saviñón',
  '¿Buscas comprar, rentar, vender o invertir en bienes raíces?',
  'Te acompaño en cada paso del proceso inmobiliario — compra, venta, renta o inversión — con estrategia, transparencia y un trato personalizado.',
  E'Con más de 3 años en el sector y el respaldo de la inmobiliaria Walls & People, combino estrategia comercial con un trato humano y transparente. Me especializo en conectar personas con propiedades que no solo cumplen expectativas, sino que sean el proyecto ideal para ellos.\n\nSoy egresado de la UDEM de la Ingeniería en Gestión Empresarial e Ingeniería Industrial y de Sistemas. Mis estudios me han ayudado a buscar maneras de resolverle problemas a mis clientes y tener mayor organización al trabajar.',
  '/images/paulo-portrait.jpg',
  null,
  '81 2862 5350',
  '528128625350',
  'paulo.leal@w-p.mx',
  'https://www.instagram.com/paulolealsav/',
  'https://www.facebook.com/people/Paulo-Leal-Bienes-Ra%C3%ADces/61572709677439/',
  'https://www.linkedin.com/in/paulo-leal-savi%C3%B1on',
  'Monterrey, N.L.',
  3,
  '[
    {"nombre": "AMPI", "descripcion": "Asociación Mexicana de Profesionales Inmobiliarios — credencial vigente."},
    {"nombre": "Walls & People", "descripcion": "Asesor inmobiliario afiliado a la inmobiliaria."}
  ]'::jsonb,
  array[
    'San Pedro Garza García',
    'Valle Oriente',
    'Cumbres',
    'Del Valle',
    'Contry',
    'Monterrey Centro'
  ],
  '{"propiedades_vendidas": 50, "transacciones": 60, "clientes": 45}'::jsonb
)
on conflict (slug) do update set
  nombre = excluded.nombre,
  headline = excluded.headline,
  bio_corta = excluded.bio_corta,
  bio_larga = excluded.bio_larga,
  foto_url = excluded.foto_url,
  banner_url = excluded.banner_url,
  telefono = excluded.telefono,
  whatsapp = excluded.whatsapp,
  email = excluded.email,
  instagram = excluded.instagram,
  facebook = excluded.facebook,
  linkedin = excluded.linkedin,
  ciudad = excluded.ciudad,
  anios_experiencia = excluded.anios_experiencia,
  certificaciones = excluded.certificaciones,
  zonas_especializacion = excluded.zonas_especializacion,
  stats = excluded.stats;

-- ---------------------------------------------------------------------------
-- Listings — 6 Monterrey area properties across the broker's key zones.
-- ---------------------------------------------------------------------------

with b as (
  select id from public.brokers where slug = 'paulo-leal'
)
insert into public.listings (
  broker_id,
  slug,
  titulo,
  descripcion,
  tipo_operacion,
  precio,
  moneda,
  tipo_propiedad,
  recamaras,
  banios,
  m2_construccion,
  m2_terreno,
  estacionamientos,
  colonia,
  ciudad,
  estado,
  lat,
  lng,
  fotos,
  amenidades,
  estado_publicacion
)
select b.id, v.* from b, (values
  (
    'departamento-torre-dana',
    'Departamento en Torre Dana',
    'Departamento de lujo en Torre Dana, uno de los desarrollos más exclusivos de Del Valle en San Pedro Garza García. Acabados de primera, ventanales de piso a techo con vistas panorámicas a la Sierra Madre, pisos de madera natural y cocina integral equipada.',
    'venta'::public.listing_operacion,
    8500000::numeric,
    'MXN',
    'Departamento',
    2,
    2::numeric,
    120::numeric,
    null::numeric,
    1,
    'Del Valle',
    'San Pedro Garza García',
    'Nuevo León',
    25.6563::numeric,
    -100.3737::numeric,
    array[]::text[],
    array['Gimnasio','Alberca','Seguridad 24/7','Roof Garden','Business Center','Áreas Verdes','Valet Parking'],
    'activo'::public.listing_estado
  ),
  (
    'departamento-saqqara',
    'Departamento en Saqqara',
    'Espectacular departamento en renta en la exclusiva zona de San Ángel en San Pedro Garza García. Tres recámaras amplias, doble estacionamiento techado y una terraza con vista abierta. Ideal para familias o ejecutivos.',
    'renta'::public.listing_operacion,
    35000::numeric,
    'MXN',
    'Departamento',
    3,
    2.5::numeric,
    180::numeric,
    null::numeric,
    2,
    'Colinas de San Jerónimo',
    'San Pedro Garza García',
    'Nuevo León',
    25.6308::numeric,
    -100.3968::numeric,
    array[]::text[],
    array['Gimnasio','Alberca','Seguridad 24/7','Pet Friendly','Áreas Verdes'],
    'activo'::public.listing_estado
  ),
  (
    'departamento-valle-oriente',
    'Departamento en Valle Oriente',
    'Moderno departamento en el corazón de Valle Oriente, a un costado del corredor financiero más importante de Monterrey. Dos recámaras amplias, cocina integral con barra desayunadora y balcón privado con vista a la ciudad.',
    'venta'::public.listing_operacion,
    6200000::numeric,
    'MXN',
    'Departamento',
    2,
    2::numeric,
    140::numeric,
    null::numeric,
    2,
    'Valle Oriente',
    'San Pedro Garza García',
    'Nuevo León',
    25.6411::numeric,
    -100.3614::numeric,
    array[]::text[],
    array['Gimnasio','Alberca','Seguridad 24/7','Roof Garden','Áreas Verdes'],
    'activo'::public.listing_estado
  ),
  (
    'casa-cumbres',
    'Casa en Cumbres',
    'Residencia familiar en Cumbres con jardín privado, cochera doble y espacios amplios. Ideal para familias que buscan tranquilidad y seguridad en una zona consolidada al poniente de Monterrey.',
    'venta'::public.listing_operacion,
    5800000::numeric,
    'MXN',
    'Casa',
    3,
    2.5::numeric,
    260::numeric,
    300::numeric,
    2,
    'Cumbres Elite',
    'Monterrey',
    'Nuevo León',
    25.7419::numeric,
    -100.4003::numeric,
    array[]::text[],
    array['Seguridad 24/7','Áreas Verdes','Pet Friendly'],
    'activo'::public.listing_estado
  ),
  (
    'departamento-contry-renta',
    'Departamento amueblado en Contry',
    'Departamento completamente amueblado en Contry, ideal para ejecutivos. Listo para habitarse con cocina equipada, lavandería y acceso a amenidades del edificio.',
    'renta'::public.listing_operacion,
    22000::numeric,
    'MXN',
    'Departamento',
    2,
    2::numeric,
    95::numeric,
    null::numeric,
    1,
    'Contry',
    'Monterrey',
    'Nuevo León',
    25.6443::numeric,
    -100.2671::numeric,
    array[]::text[],
    array['Gimnasio','Alberca','Seguridad 24/7','Áreas Verdes','Salón de Usos Múltiples'],
    'activo'::public.listing_estado
  ),
  (
    'loft-zona-centro',
    'Loft en Zona Centro',
    'Loft contemporáneo en el corazón del centro de Monterrey, caminable a bares, restaurantes y oficinas corporativas. Distribución abierta, doble altura y acabados industriales.',
    'renta'::public.listing_operacion,
    18500::numeric,
    'MXN',
    'Departamento',
    1,
    1::numeric,
    70::numeric,
    null::numeric,
    1,
    'Centro',
    'Monterrey',
    'Nuevo León',
    25.6714::numeric,
    -100.3095::numeric,
    array[]::text[],
    array['Seguridad 24/7','Roof Garden'],
    'activo'::public.listing_estado
  )
) as v(
  slug,
  titulo,
  descripcion,
  tipo_operacion,
  precio,
  moneda,
  tipo_propiedad,
  recamaras,
  banios,
  m2_construccion,
  m2_terreno,
  estacionamientos,
  colonia,
  ciudad,
  estado,
  lat,
  lng,
  fotos,
  amenidades,
  estado_publicacion
)
on conflict (broker_id, slug) do update set
  titulo = excluded.titulo,
  descripcion = excluded.descripcion,
  tipo_operacion = excluded.tipo_operacion,
  precio = excluded.precio,
  moneda = excluded.moneda,
  tipo_propiedad = excluded.tipo_propiedad,
  recamaras = excluded.recamaras,
  banios = excluded.banios,
  m2_construccion = excluded.m2_construccion,
  m2_terreno = excluded.m2_terreno,
  estacionamientos = excluded.estacionamientos,
  colonia = excluded.colonia,
  ciudad = excluded.ciudad,
  estado = excluded.estado,
  lat = excluded.lat,
  lng = excluded.lng,
  fotos = excluded.fotos,
  amenidades = excluded.amenidades,
  estado_publicacion = excluded.estado_publicacion;

commit;
